variables:
  product_name: "qcow2fileBuild"

stages:
  - buildAndDeploy


buildAndDeploy:
  except:
    - tags
  stage: buildAndDeploy
  script:
    - cd build;echo `./qcow2file_linux_amd64.sh`
    - cd ../pkg/;smbclient //192.168.200.100/share -D ztest/tools -c 'put qcow2file' -U=smb%password

