name: Go

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: denpendency
      run: sudo apt install libvirt-dev -y

    - name: build
      run: cd build;./qcow2file_linux_amd64.sh

    - name: Get current tag
      run: |
        current_tag=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
        echo "Current tag is $current_tag"

    - name: Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: $current_tag
        release_name: $current_tag
        draft: false
        prerelease: false
        assets: pkg/qcow2file
